### ISSUE TITLE
`read_xml()` for any `R: Read` or `R: BufRead`, instead of `&str`?

### ISSUE THREAD

**Issue by lo48576** [johnstonskj/rust-xml_dom#10]
It would be possible to attempt to parse a large file which is not known to be an XML (and expected to fail quickly if not an XML).
However, the current `fn read_xml(_: &str) -> Result<_, _>` requires all the bytes loaded on a contiguous memory region.
For such situation, it would be better if `read_xml()` or similar function reads a document from reader types with `Read` or `BufRead` trait impl, rather than from `&str`.

Is it planned to be supported, or is there any difficulties?

**Comment by johnstonskj** [comment]
It can be done, it wasn't an initial use case for the need I had, but I can add it for sure. Thanks.

**Comment by johnstonskj** [comment]
See https://github.com/johnstonskj/rust-xml_dom/commit/8fab039b5d7e8a9487421a3906c31f2a026ea688

**Comment by johnstonskj** [comment]
All tests passing, published to crates.io as 0.2.5.
