### ISSUE TITLE
Documentation mismatch for get_implementation_ext

### ISSUE THREAD

**Issue by wyf18** [johnstonskj/rust-xml_dom#18]
Hello! 🐙
While scanning crates.io. we noticed a document-code mismatch issue in this crate, we think the doc examples are generally meant to illustrate why someone would want to use the item.

# Location

documentation for xml_dom::level2::ext::dom_impl::[get_implementation_ext](https://docs.rs/xml_dom/0.2.6/xml_dom/level2/ext/dom_impl/fn.get_implementation_ext.html)

# Summary

The example of the document does not mention the `get_implementation_ext` function, it is not clear how to use it.

Thank you for checking out this issue! 👍🤗

**Comment by johnstonskj** [comment]
Sorry it took so long, this is fixed in 2dd3dbd in v0.2.8
