### ISSUE TITLE
`Document::document_element` returns a wrong node

### ISSUE THREAD

**Issue by kawadakk** [johnstonskj/rust-xml_dom#19]
## Describe the bug

If a document element is preceded by a comment node, `Document::document_element` returns the comment node instead of the document element.

## Minimal Reproducible Examples (MRE)

```rust
use xml_dom::level2::*;
let doc = xml_dom::parser::read_xml(r#"
    <?xml version="1.0" ?>
    <!-- comment -->
    <document />
"#).unwrap();
assert_eq!(doc.document_element().unwrap().node_type(), NodeType::Element);
```

```
thread 'hoge' panicked at 'assertion failed: `(left == right)`
  left: `Comment`,
 right: `Element`', src/lib.rs:9:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Environment (please complete the following information):**
 - Platform: `Linux {hostname} 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux`
 - Rust: `rustc 1.68.0-nightly (3020239de 2023-01-09)`
 - Cargo: `cargo 1.68.0-nightly (8c460b223 2023-01-04)`

## Additional context

N/A

**Comment by johnstonskj** [comment]
Fixed in [9019d78](https://github.com/johnstonskj/rust-xml_dom/commit/9019d78029dc756c5437ec14429d2b7e0c555944), your MRE is included as a regression test.
